"""add_users_table

Revision ID: 709b073db8d0
Revises: 001
Create Date: 2025-12-24 20:00:50.402508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '709b073db8d0'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('pipelines', sa.Column('target_table_mapping', sa.JSON(), nullable=True))
    op.alter_column('pipelines', 'status',
               existing_type=postgresql.ENUM('STOPPED', 'STARTING', 'RUNNING', 'STOPPING', 'ERROR', name='pipelinestatus'),
               nullable=True)
    op.drop_constraint(op.f('pipelines_name_key'), 'pipelines', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('pipelines_name_key'), 'pipelines', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('pipelines', 'status',
               existing_type=postgresql.ENUM('STOPPED', 'STARTING', 'RUNNING', 'STOPPING', 'ERROR', name='pipelinestatus'),
               nullable=False)
    op.drop_column('pipelines', 'target_table_mapping')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
